### ISSUE TITLE
Key Rotation Issue

### ISSUE THREAD

**Issue by Akoasm666** [MurphyAdam/encrypted-json-field#1]
Does this class support key rotation?

**Comment by MurphyAdam** [comment]
Hey @Akoasm666, no, that's not supported at the moment.

**Comment by Akoasm666** [comment]
Ok thanks.

**Comment by GTMany** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xkubov, @gubloon, @Bongulielmi, @alphasierra59, @wangfangde, @filipsuk, @maqz9999, @dhelbegor, @Nutza97, @Shahidaleem, @partyka1, @M1nd3r, @kyehyukahn, @tokenscienceai, @johngb, @joshrdawson, @wy-z, @random-zebra, @hynek-jina, @durk1234, @Muhammet2700d, @mys, @julianosilva94, @Koistinen, @enrbh, @MichelSakr, @tumelo-mapheto, @lishuai87, @margre8, @dave-lanigan, @luca-regne, @krittakondev, @maxmousee, @Tomwslape5638, @nekofar, @wangke0809, @raymonddurk, @Ivshti, @Mehrnazibi, @funwun, @luicer, @stechu, @afozbek, @watchzerg, @TheArhaam, @reason-tech, @compreidollar, @alagiz, @agamkohli9, @1-bit-wonder
